swagger: "2.0"
info:
  description: "."
  version: "1.0.0"
  title: ""
  termsOfService: "/"
  contact:
    email: "emre.cakmak@ug.bilkent.edu.tr"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

host: "localhost:8888"
basePath: "/slimFW/api"
schemes:
  - "http"

paths:
  /course/{courseid}:
    get:
      tags:
        - "getCourse"
      summary: ""
      description: ""
      operationId: ""
      produces:
        - "application/json"
      parameters:
      
        - name: "courseid"
          in: "path"
          description: "ID of book will be fetched"
          required: true
          type: "integer"
          format: "int64"

      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/X"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Order not found"

definitions:
  X:
    type: "object"
    properties:
      id:
        type: "integer"
      title:
        type: "string"
      couponCode:
        type: "string"
      price:
        type: "integer"
